[581266] Validation action should be disabled until there is a selection
Otherwise we get this when the action is run without a selection:
NullPointerException: Cannot invoke "java.util.List.size()" because
"this.selectedObjects" is null